adress_url: http://maps.ufanet.ru/orenburg#1759214666SGR59
time_begin: 06:00
time_end: 14:40
time_period_interval: 1.0
time_video: 14:45
video_fps: 60
delete_frames_after_video: true
image_quality: 92
